# Generated by Django 2.2.6 on 2019-10-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mdcb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='occupation',
            field=models.CharField(choices=[('Physicist', 'Physicist'), ('Dosimetrist', 'Dosimetrist'), ('Radiation Therapist', 'Radiation Therapist'), ('Radiation Oncologist', 'Radiation Oncologist'), ('Other', 'Other')], default='Physicist', max_length=30),
        ),
    ]
