# Generated by Django 2.2.6 on 2019-10-21 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=400)),
                ('isSAM', models.BooleanField()),
                ('isCAMPEP', models.BooleanField()),
                ('isMDCB', models.BooleanField()),
                ('start_datetime', models.DateTimeField(verbose_name='start time')),
                ('end_datetime', models.DateTimeField(verbose_name='end time')),
                ('CAMPEPReferenceID', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='events',
            old_name='urlshortEvents',
            new_name='urlshort',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='urlshortOrganization',
            new_name='urlshort',
        ),
        migrations.AlterField(
            model_name='attendance_session',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cme.session'),
        ),
        migrations.AlterField(
            model_name='evaluation_speaker',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cme.session'),
        ),
        migrations.AlterField(
            model_name='samquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cme.session'),
        ),
        migrations.DeleteModel(
            name='event',
        ),
        migrations.AddField(
            model_name='session',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cme.Events'),
        ),
        migrations.AddField(
            model_name='session',
            name='presenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
