# Generated by Django 2.2.6 on 2019-10-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0002_auto_20191020_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_session',
            name='attendee',
        ),
        migrations.AddField(
            model_name='evaluation_speaker',
            name='additionalComments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='samquestion',
            name='reference',
            field=models.TextField(default='', max_length=900),
            preserve_default=False,
        ),
    ]
