# Generated by Django 2.2.6 on 2019-10-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cme', '0004_samresults'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_session',
            name='needCAMPEP',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance_session',
            name='needMDCB',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance_session',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
